Bug #1079807 clk: resolve warning of "unused variable"
[self test   ] L.A.V.A
[change_type ] r&d

Fix <f114a36246812b5c06b0a6066412215e45b3ac8c>

build_error:
/space/builder/repo/build_0_7642/code/bsp/kernel/kernel4.14/drivers/clk/clk.c:48:27:
error: unused variable 'orphan_list' [-Werror,-Wunused-variable]

When CONFIG_DEBUG_FS is disabled, above warning will be generated.

Change-Id: I694f2ee6b2b458aceaafa911bccba0cd7aa4182d
Signed-off-by: Orson Zhai <orson.zhai@unisoc.com>